from django.urls import path

from .views import HomeList, HomeDetails, BookList, BookDetails, VideosList, VideosDetails, PodcastsList, PodcastsDetails, BiologyList, BiologyDetails, ChemistryList, ChemistryDetails, EnglishList, EnglishDetails, MathematicsList, MathematicsDetails, PhysicsList, PhysicsDetails, BiNqList, BiNqDetails, ChNqList, ChNqDetails, CsNqList, CsNqDetails, LaNqList, LaNqDetails, MaNqList, MaNqDetails, PhNqList, PhNqDetails, AnatomyOneList, AnatomyOneDetails, BiochemistryOneList, BiochemistryOneDetails, ClinicalScienceOneList, ClinicalScienceOneDetails, DiagnosticsOneList, DiagnosticsOneDetails, LabScienceOneList, LabScienceOneDetails, PathologyOneList, PathologyOneDetails, PhysiologyOneList, PhysiologyOneDetails, PublicHealthOneList, PublicHealthOneDetails, SocietyAndMedicineOneList, SocietyAndMedicineOneDetails, TherapeuticsOneList, TherapeuticsOneDetails, AnatomyTwoList, AnatomyTwoDetails, BiochemistryTwoList, BiochemistryTwoDetails, ClinicalScienceTwoList, ClinicalScienceTwoDetails, DiagnosticsTwoList, DiagnosticsTwoDetails, LabScienceTwoList, LabScienceTwoDetails, PathologyTwoList, PathologyTwoDetails, PhysiologyTwoList, PhysiologyTwoDetails, PublicHealthTwoList, PublicHealthTwoDetails, SocietyAndMedicineTwoList, SocietyAndMedicineTwoDetails, TherapeuticsTwoList, TherapeuticsTwoDetails, AnatomyOnetbtList, AnatomyOnetbtDetails, BiochemistryOnetbtList, BiochemistryOnetbtDetails, ClinicalScienceOnetbtList, ClinicalScienceOnetbtDetails, DiagnosticsOnetbtList, DiagnosticsOnetbtDetails, LabScienceOnetbtList, LabScienceOnetbtDetails, PathologyOnetbtList, PathologyOnetbtDetails, PhysiologyOnetbtList, PhysiologyOnetbtDetails, PublicHealthOnetbtList, PublicHealthOnetbtDetails, SocietyAndMedicineOnetbtList, SocietyAndMedicineOnetbtDetails, TherapeuticsOnetbtList, TherapeuticsOnetbtDetails, AnatomyTwotbtList, AnatomyTwotbtDetails, BiochemistryTwotbtList, BiochemistryTwotbtDetails, ClinicalScienceTwotbtList, ClinicalScienceTwotbtDetails, DiagnosticsTwotbtList, DiagnosticsTwotbtDetails, LabScienceTwotbtList, LabScienceTwotbtDetails, PathologyTwotbtList, PathologyTwotbtDetails, PhysiologyTwotbtList, PhysiologyTwotbtDetails, PublicHealthTwotbtList, PublicHealthTwotbtDetails, SocietyAndMedicineTwotbtList, SocietyAndMedicineTwotbtDetails, TherapeuticsTwotbtList, TherapeuticsTwotbtDetails


urlpatterns = [
    path('HomeApiList/', HomeList.as_view({'get':'list', 'post': 'create'})),
    path('HomeApiDetail/<int:id>/', HomeDetails.as_view({'get':'retrieve', 'put': 'update', 'patch': 'partial_update', 'delete': 'destroy'})),
    path('BookApiList/', BookList.as_view({'get':'list', 'post': 'create'})),
    path('BookApiDetail/<int:id>/', BookDetails.as_view({'get':'retrieve', 'put': 'update', 'patch': 'partial_update', 'delete': 'destroy'})),
    path('VideosApiList/', VideosList.as_view({'get':'list', 'post': 'create'})),
    path('VideosApiDetail/<int:id>/', VideosDetails.as_view({'get':'retrieve', 'put': 'update', 'patch': 'partial_update', 'delete': 'destroy'})),
    path('PodcastsApiList/', PodcastsList.as_view({'get':'list', 'post': 'create'})),
    path('PodcastsApiDetail/<int:id>/', PodcastsDetails.as_view({'get':'retrieve', 'put': 'update', 'patch': 'partial_update', 'delete': 'destroy'})),
    path('BiologyApiList/', BiologyList.as_view({'get':'list', 'post': 'create'})),
    path('BiologyApiDetail/<int:id>/', BiologyDetails.as_view({'get':'retrieve', 'put': 'update', 'patch': 'partial_update', 'delete': 'destroy'})),
    path('ChemistryApiList/', ChemistryList.as_view({'get':'list', 'post': 'create'})),
    path('ChemistryApiDetail/<int:id>/', ChemistryDetails.as_view({'get':'retrieve', 'put': 'update', 'patch': 'partial_update', 'delete': 'destroy'})),
    path('MathematicsApiList/', MathematicsList.as_view({'get':'list', 'post': 'create'})),
    path('MathematicsApiDetail/<int:id>/', MathematicsDetails.as_view({'get':'retrieve', 'put': 'update', 'patch': 'partial_update', 'delete': 'destroy'})),
    path('PhysicsApiList/', PhysicsList.as_view({'get':'list', 'post': 'create'})),
    path('PhysicsApiDetail/<int:id>/', PhysicsDetails.as_view({'get':'retrieve', 'put': 'update', 'patch': 'partial_update', 'delete': 'destroy'})),
    path('BiNqApiList/', BiNqList.as_view({'get':'list', 'post': 'create'})),
    path('BiNqApiDetail/<int:id>/', BiNqDetails.as_view({'get':'retrieve', 'put': 'update', 'patch': 'partial_update', 'delete': 'destroy'})),
    path('ChNqApiList/', ChNqList.as_view({'get':'list', 'post': 'create'})),
    path('ChNqApiDetail/<int:id>/', ChNqDetails.as_view({'get':'retrieve', 'put': 'update', 'patch': 'partial_update', 'delete': 'destroy'})),
    path('CsNqApiList/', CsNqList.as_view({'get':'list', 'post': 'create'})),
    path('CsNqApiDetail/<int:id>/', CsNqDetails.as_view({'get':'retrieve', 'put': 'update', 'patch': 'partial_update', 'delete': 'destroy'})),
    path('LaNqApiList/', LaNqList.as_view({'get':'list', 'post': 'create'})),
    path('LaNqApiDetail/<int:id>/', LaNqDetails.as_view({'get':'retrieve', 'put': 'update', 'patch': 'partial_update', 'delete': 'destroy'})),
    path('MaNqApiList/', MaNqList.as_view({'get':'list', 'post': 'create'})),
    path('MaNqApiDetail/<int:id>/', MaNqDetails.as_view({'get':'retrieve', 'put': 'update', 'patch': 'partial_update', 'delete': 'destroy'})),
    path('PhNqApiList/', PhNqList.as_view({'get':'list', 'post': 'create'})),
    path('PhNqApiDetail/<int:id>/', PhNqDetails.as_view({'get':'retrieve', 'put': 'update', 'patch': 'partial_update', 'delete': 'destroy'})),
    path('AnatomyOneApiList/', AnatomyOneList.as_view({'get':'list', 'post': 'create'})),
    path('AnatomyOneApiDetail/<int:id>/', AnatomyOneDetails.as_view({'get':'retrieve', 'put': 'update', 'patch': 'partial_update', 'delete': 'destroy'})),
    path('BiochemistryOneApiList/', BiochemistryOneList.as_view({'get':'list', 'post': 'create'})),
    path('BiochemistryOneApiDetail/<int:id>/', BiochemistryOneDetails.as_view({'get':'retrieve', 'put': 'update', 'patch': 'partial_update', 'delete': 'destroy'})),
    path('ClinicalScienceOneApiList/', ClinicalScienceOneList.as_view({'get':'list', 'post': 'create'})),
    path('ClinicalScienceOneApiDetail/<int:id>/', ClinicalScienceOneDetails.as_view({'get':'retrieve', 'put': 'update', 'patch': 'partial_update', 'delete': 'destroy'})),
    path('DiagnosticsOneApiList/', DiagnosticsOneList.as_view({'get':'list', 'post': 'create'})),
    path('DiagnosticsOneApiDetail/<int:id>/', DiagnosticsOneDetails.as_view({'get':'retrieve', 'put': 'update', 'patch': 'partial_update', 'delete': 'destroy'})),
    path('LabScienceOneApiList/', LabScienceOneList.as_view({'get':'list', 'post': 'create'})),
    path('LabScienceOneApiDetail/<int:id>/', LabScienceOneDetails.as_view({'get':'retrieve', 'put': 'update', 'patch': 'partial_update', 'delete': 'destroy'})),
    path('PathologyOneApiList/', PathologyOneList.as_view({'get':'list', 'post': 'create'})),
    path('PathologyOneApiDetail/<int:id>/', PathologyOneDetails.as_view({'get':'retrieve', 'put': 'update', 'patch': 'partial_update', 'delete': 'destroy'})),
    path('PhysiologyOneApiList/', PhysiologyOneList.as_view({'get':'list', 'post': 'create'})),
    path('PhysiologyOneApiDetail/<int:id>/', PhysiologyOneDetails.as_view({'get':'retrieve', 'put': 'update', 'patch': 'partial_update', 'delete': 'destroy'})),
    path('PublicHealthOneApiList/', PublicHealthOneList.as_view({'get':'list', 'post': 'create'})),
    path('PublicHealthOneApiDetail/<int:id>/', PublicHealthOneDetails.as_view({'get':'retrieve', 'put': 'update', 'patch': 'partial_update', 'delete': 'destroy'})),
    path('SocietyAndMedicineOneApiList/', SocietyAndMedicineOneList.as_view({'get':'list', 'post': 'create'})),
    path('SocietyAndMedicineOneApiDetail/<int:id>/', SocietyAndMedicineOneDetails.as_view({'get':'retrieve', 'put': 'update', 'patch': 'partial_update', 'delete': 'destroy'})),
    path('TherapeuticsOneApiList/', TherapeuticsOneList.as_view({'get':'list', 'post': 'create'})),
    path('TherapeuticsOneApiDetail/<int:id>/', TherapeuticsOneDetails.as_view({'get':'retrieve', 'put': 'update', 'patch': 'partial_update', 'delete': 'destroy'})),
    path('AnatomyTwoApiList/', AnatomyTwoList.as_view({'get':'list', 'post': 'create'})),
    path('AnatomyTwoApiDetail/<int:id>/', AnatomyTwoDetails.as_view({'get':'retrieve', 'put': 'update', 'patch': 'partial_update', 'delete': 'destroy'})),
    path('BiochemistryTwoApiList/', BiochemistryTwoList.as_view({'get':'list', 'post': 'create'})),
    path('BiochemistryTwoApiDetail/<int:id>/', BiochemistryTwoDetails.as_view({'get':'retrieve', 'put': 'update', 'patch': 'partial_update', 'delete': 'destroy'})),
    path('ClinicalScienceTwoApiList/', ClinicalScienceTwoList.as_view({'get':'list', 'post': 'create'})),
    path('ClinicalScienceTwoApiDetail/<int:id>/', ClinicalScienceTwoDetails.as_view({'get':'retrieve', 'put': 'update', 'patch': 'partial_update', 'delete': 'destroy'})),
    path('DiagnosticsTwoApiList/', DiagnosticsTwoList.as_view({'get':'list', 'post': 'create'})),
    path('DiagnosticsTwoApiDetail/<int:id>/', DiagnosticsTwoDetails.as_view({'get':'retrieve', 'put': 'update', 'patch': 'partial_update', 'delete': 'destroy'})),
    path('LabScienceTwoApiList/', LabScienceTwoList.as_view({'get':'list', 'post': 'create'})),
    path('LabScienceTwoApiDetail/<int:id>/', LabScienceTwoDetails.as_view({'get':'retrieve', 'put': 'update', 'patch': 'partial_update', 'delete': 'destroy'})),
    path('PathologyTwoApiList/', PathologyTwoList.as_view({'get':'list', 'post': 'create'})),
    path('PathologyTwoApiDetail/<int:id>/', PathologyTwoDetails.as_view({'get':'retrieve', 'put': 'update', 'patch': 'partial_update', 'delete': 'destroy'})),
    path('PhysiologyTwoApiList/', PhysiologyTwoList.as_view({'get':'list', 'post': 'create'})),
    path('PhysiologyTwoApiDetail/<int:id>/', PhysiologyTwoDetails.as_view({'get':'retrieve', 'put': 'update', 'patch': 'partial_update', 'delete': 'destroy'})),
    path('PublicHealthTwoApiList/', PublicHealthTwoList.as_view({'get':'list', 'post': 'create'})),
    path('PublicHealthTwoApiDetail/<int:id>/', PublicHealthTwoDetails.as_view({'get':'retrieve', 'put': 'update', 'patch': 'partial_update', 'delete': 'destroy'})),
    path('SocietyAndMedicineTwoApiList/', SocietyAndMedicineTwoList.as_view({'get':'list', 'post': 'create'})),
    path('SocietyAndMedicineTwoApiDetail/<int:id>/', SocietyAndMedicineTwoDetails.as_view({'get':'retrieve', 'put': 'update', 'patch': 'partial_update', 'delete': 'destroy'})),
    path('TherapeuticsTwoApiList/', TherapeuticsTwoList.as_view({'get':'list', 'post': 'create'})),
    path('TherapeuticsTwoApiDetail/<int:id>/', TherapeuticsTwoDetails.as_view({'get':'retrieve', 'put': 'update', 'patch': 'partial_update', 'delete': 'destroy'})),
    path('AnatomyOnetbtApiList/', AnatomyOnetbtList.as_view({'get':'list', 'post': 'create'})),
    path('AnatomyOnetbtApiDetail/<int:id>/', AnatomyOnetbtDetails.as_view({'get':'retrieve', 'put': 'update', 'patch': 'partial_update', 'delete': 'destroy'})),
    path('BiochemistryOnetbtApiList/', BiochemistryOnetbtList.as_view({'get':'list', 'post': 'create'})),
    path('BiochemistryOnetbtApiDetail/<int:id>/', BiochemistryOnetbtDetails.as_view({'get':'retrieve', 'put': 'update', 'patch': 'partial_update', 'delete': 'destroy'})),
    path('ClinicalScienceOnetbtApiList/', ClinicalScienceOnetbtList.as_view({'get':'list', 'post': 'create'})),
    path('ClinicalScienceOnetbtApiDetail/<int:id>/', ClinicalScienceOnetbtDetails.as_view({'get':'retrieve', 'put': 'update', 'patch': 'partial_update', 'delete': 'destroy'})),
    path('DiagnosticsOnetbtApiList/', DiagnosticsOnetbtList.as_view({'get':'list', 'post': 'create'})),
    path('DiagnosticsOnetbtApiDetail/<int:id>/', DiagnosticsOnetbtDetails.as_view({'get':'retrieve', 'put': 'update', 'patch': 'partial_update', 'delete': 'destroy'})),
    path('LabScienceOnetbtApiList/', LabScienceOnetbtList.as_view({'get':'list', 'post': 'create'})),
    path('LabScienceOnetbtApiDetail/<int:id>/', LabScienceOnetbtDetails.as_view({'get':'retrieve', 'put': 'update', 'patch': 'partial_update', 'delete': 'destroy'})),
    path('PathologyOnetbtApiList/', PathologyOnetbtList.as_view({'get':'list', 'post': 'create'})),
    path('PathologyOnetbtApiDetail/<int:id>/', PathologyOnetbtDetails.as_view({'get':'retrieve', 'put': 'update', 'patch': 'partial_update', 'delete': 'destroy'})),
    path('PhysiologyOnetbtApiList/', PhysiologyOnetbtList.as_view({'get':'list', 'post': 'create'})),
    path('PhysiologyOnetbtApiDetail/<int:id>/', PhysiologyOnetbtDetails.as_view({'get':'retrieve', 'put': 'update', 'patch': 'partial_update', 'delete': 'destroy'})),
    path('PublicHealthOnetbtApiList/', PublicHealthOnetbtList.as_view({'get':'list', 'post': 'create'})),
    path('PublicHealthOnetbtApiDetail/<int:id>/', PublicHealthOnetbtDetails.as_view({'get':'retrieve', 'put': 'update', 'patch': 'partial_update', 'delete': 'destroy'})),
    path('SocietyAndMedicineOnetbtApiList/', SocietyAndMedicineOnetbtList.as_view({'get':'list', 'post': 'create'})),
    path('SocietyAndMedicineOnetbtApiDetail/<int:id>/', SocietyAndMedicineOnetbtDetails.as_view({'get':'retrieve', 'put': 'update', 'patch': 'partial_update', 'delete': 'destroy'})),
    path('TherapeuticsOnetbtApiList/', TherapeuticsOnetbtList.as_view({'get':'list', 'post': 'create'})),
    path('TherapeuticsOnetbtApiDetail/<int:id>/', TherapeuticsOnetbtDetails.as_view({'get':'retrieve', 'put': 'update', 'patch': 'partial_update', 'delete': 'destroy'})),
    path('AnatomyTwotbtApiList/', AnatomyTwotbtList.as_view({'get':'list', 'post': 'create'})),
    path('AnatomyTwotbtApiDetail/<int:id>/', AnatomyTwotbtDetails.as_view({'get':'retrieve', 'put': 'update', 'patch': 'partial_update', 'delete': 'destroy'})),
    path('BiochemistryTwotbtApiList/', BiochemistryTwotbtList.as_view({'get':'list', 'post': 'create'})),
    path('BiochemistryTwotbtApiDetail/<int:id>/', BiochemistryTwotbtDetails.as_view({'get':'retrieve', 'put': 'update', 'patch': 'partial_update', 'delete': 'destroy'})),
    path('ClinicalScienceTwotbtApiList/', ClinicalScienceTwotbtList.as_view({'get':'list', 'post': 'create'})),
    path('ClinicalScienceTwotbtApiDetail/<int:id>/', ClinicalScienceTwotbtDetails.as_view({'get':'retrieve', 'put': 'update', 'patch': 'partial_update', 'delete': 'destroy'})),
    path('DiagnosticsTwotbtApiList/', DiagnosticsTwotbtList.as_view({'get':'list', 'post': 'create'})),
    path('DiagnosticsTwotbtApiDetail/<int:id>/', DiagnosticsTwotbtDetails.as_view({'get':'retrieve', 'put': 'update', 'patch': 'partial_update', 'delete': 'destroy'})),
    path('LabScienceTwotbtApiList/', LabScienceTwotbtList.as_view({'get':'list', 'post': 'create'})),
    path('LabScienceTwotbtApiDetail/<int:id>/', LabScienceTwotbtDetails.as_view({'get':'retrieve', 'put': 'update', 'patch': 'partial_update', 'delete': 'destroy'})),
    path('PathologyTwotbtApiList/', PathologyTwotbtList.as_view({'get':'list', 'post': 'create'})),
    path('PathologyTwotbtApiDetail/<int:id>/', PathologyTwotbtDetails.as_view({'get':'retrieve', 'put': 'update', 'patch': 'partial_update', 'delete': 'destroy'})),
    path('PhysiologyTwotbtApiList/', PhysiologyTwotbtList.as_view({'get':'list', 'post': 'create'})),
    path('PhysiologyTwotbtApiDetail/<int:id>/', PhysiologyTwotbtDetails.as_view({'get':'retrieve', 'put': 'update', 'patch': 'partial_update', 'delete': 'destroy'})),
    path('PublicHealthTwotbtApiList/', PublicHealthTwotbtList.as_view({'get':'list', 'post': 'create'})),
    path('PublicHealthTwotbtApiDetail/<int:id>/', PublicHealthTwotbtDetails.as_view({'get':'retrieve', 'put': 'update', 'patch': 'partial_update', 'delete': 'destroy'})),
    path('SocietyAndMedicineTwotbtApiList/', SocietyAndMedicineTwotbtList.as_view({'get':'list', 'post': 'create'})),
    path('SocietyAndMedicineTwotbtApiDetail/<int:id>/', SocietyAndMedicineTwotbtDetails.as_view({'get':'retrieve', 'put': 'update', 'patch': 'partial_update', 'delete': 'destroy'})),
    path('TherapeuticsTwotbtApiList/', TherapeuticsTwotbtList.as_view({'get':'list', 'post': 'create'})),
    path('TherapeuticsTwotbtApiDetail/<int:id>/', TherapeuticsTwotbtDetails.as_view({'get':'retrieve', 'put': 'update', 'patch': 'partial_update', 'delete': 'destroy'})),


]
