# Generated by Django 5.2 on 2025-05-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_anatomyone_anatomytwo_binq_biochemistryone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnatomyOnetbt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen', models.CharField(blank=True, max_length=500, null=True)),
                ('extraOne', models.TextField(blank=True, null=True)),
                ('extraTwo', models.TextField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('textOne', models.TextField(blank=True, null=True)),
                ('textOneLink', models.TextField(blank=True, null=True)),
                ('extraThree', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnatomyTwotbt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen', models.CharField(blank=True, max_length=500, null=True)),
                ('extraOne', models.TextField(blank=True, null=True)),
                ('extraTwo', models.TextField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('textOne', models.TextField(blank=True, null=True)),
                ('textOneLink', models.TextField(blank=True, null=True)),
                ('extraThree', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BiochemistryOnetbt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen', models.CharField(blank=True, max_length=500, null=True)),
                ('extraOne', models.TextField(blank=True, null=True)),
                ('extraTwo', models.TextField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('textOne', models.TextField(blank=True, null=True)),
                ('textOneLink', models.TextField(blank=True, null=True)),
                ('extraThree', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BiochemistryTwotbt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen', models.CharField(blank=True, max_length=500, null=True)),
                ('extraOne', models.TextField(blank=True, null=True)),
                ('extraTwo', models.TextField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('textOne', models.TextField(blank=True, null=True)),
                ('textOneLink', models.TextField(blank=True, null=True)),
                ('extraThree', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClinicalScienceOnetbt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen', models.CharField(blank=True, max_length=500, null=True)),
                ('extraOne', models.TextField(blank=True, null=True)),
                ('extraTwo', models.TextField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('textOne', models.TextField(blank=True, null=True)),
                ('textOneLink', models.TextField(blank=True, null=True)),
                ('extraThree', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClinicalScienceTwotbt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen', models.CharField(blank=True, max_length=500, null=True)),
                ('extraOne', models.TextField(blank=True, null=True)),
                ('extraTwo', models.TextField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('textOne', models.TextField(blank=True, null=True)),
                ('textOneLink', models.TextField(blank=True, null=True)),
                ('extraThree', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosticsOnetbt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen', models.CharField(blank=True, max_length=500, null=True)),
                ('extraOne', models.TextField(blank=True, null=True)),
                ('extraTwo', models.TextField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('textOne', models.TextField(blank=True, null=True)),
                ('textOneLink', models.TextField(blank=True, null=True)),
                ('extraThree', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosticsTwotbt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen', models.CharField(blank=True, max_length=500, null=True)),
                ('extraOne', models.TextField(blank=True, null=True)),
                ('extraTwo', models.TextField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('textOne', models.TextField(blank=True, null=True)),
                ('textOneLink', models.TextField(blank=True, null=True)),
                ('extraThree', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LabScienceOnetbt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen', models.CharField(blank=True, max_length=500, null=True)),
                ('extraOne', models.TextField(blank=True, null=True)),
                ('extraTwo', models.TextField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('textOne', models.TextField(blank=True, null=True)),
                ('textOneLink', models.TextField(blank=True, null=True)),
                ('extraThree', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LabScienceTwotbt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen', models.CharField(blank=True, max_length=500, null=True)),
                ('extraOne', models.TextField(blank=True, null=True)),
                ('extraTwo', models.TextField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('textOne', models.TextField(blank=True, null=True)),
                ('textOneLink', models.TextField(blank=True, null=True)),
                ('extraThree', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PathologyOnetbt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen', models.CharField(blank=True, max_length=500, null=True)),
                ('extraOne', models.TextField(blank=True, null=True)),
                ('extraTwo', models.TextField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('textOne', models.TextField(blank=True, null=True)),
                ('textOneLink', models.TextField(blank=True, null=True)),
                ('extraThree', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PathologyTwotbt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen', models.CharField(blank=True, max_length=500, null=True)),
                ('extraOne', models.TextField(blank=True, null=True)),
                ('extraTwo', models.TextField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('textOne', models.TextField(blank=True, null=True)),
                ('textOneLink', models.TextField(blank=True, null=True)),
                ('extraThree', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhysiologyOnetbt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen', models.CharField(blank=True, max_length=500, null=True)),
                ('extraOne', models.TextField(blank=True, null=True)),
                ('extraTwo', models.TextField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('textOne', models.TextField(blank=True, null=True)),
                ('textOneLink', models.TextField(blank=True, null=True)),
                ('extraThree', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhysiologyTwotbt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen', models.CharField(blank=True, max_length=500, null=True)),
                ('extraOne', models.TextField(blank=True, null=True)),
                ('extraTwo', models.TextField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('textOne', models.TextField(blank=True, null=True)),
                ('textOneLink', models.TextField(blank=True, null=True)),
                ('extraThree', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PublicHealthOnetbt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen', models.CharField(blank=True, max_length=500, null=True)),
                ('extraOne', models.TextField(blank=True, null=True)),
                ('extraTwo', models.TextField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('textOne', models.TextField(blank=True, null=True)),
                ('textOneLink', models.TextField(blank=True, null=True)),
                ('extraThree', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PublicHealthTwotbt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen', models.CharField(blank=True, max_length=500, null=True)),
                ('extraOne', models.TextField(blank=True, null=True)),
                ('extraTwo', models.TextField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('textOne', models.TextField(blank=True, null=True)),
                ('textOneLink', models.TextField(blank=True, null=True)),
                ('extraThree', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocietyAndMedicineOnetbt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen', models.CharField(blank=True, max_length=500, null=True)),
                ('extraOne', models.TextField(blank=True, null=True)),
                ('extraTwo', models.TextField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('textOne', models.TextField(blank=True, null=True)),
                ('textOneLink', models.TextField(blank=True, null=True)),
                ('extraThree', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocietyAndMedicineTwotbt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen', models.CharField(blank=True, max_length=500, null=True)),
                ('extraOne', models.TextField(blank=True, null=True)),
                ('extraTwo', models.TextField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('textOne', models.TextField(blank=True, null=True)),
                ('textOneLink', models.TextField(blank=True, null=True)),
                ('extraThree', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TherapeuticsOnetbt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen', models.CharField(blank=True, max_length=500, null=True)),
                ('extraOne', models.TextField(blank=True, null=True)),
                ('extraTwo', models.TextField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('textOne', models.TextField(blank=True, null=True)),
                ('textOneLink', models.TextField(blank=True, null=True)),
                ('extraThree', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TherapeuticsTwotbt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen', models.CharField(blank=True, max_length=500, null=True)),
                ('extraOne', models.TextField(blank=True, null=True)),
                ('extraTwo', models.TextField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('textOne', models.TextField(blank=True, null=True)),
                ('textOneLink', models.TextField(blank=True, null=True)),
                ('extraThree', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='anatomyone',
            name='revisionQuestions',
        ),
        migrations.RemoveField(
            model_name='anatomyone',
            name='revisionQuestionsText',
        ),
        migrations.RemoveField(
            model_name='anatomyone',
            name='revisionQuestionsTextLink',
        ),
        migrations.RemoveField(
            model_name='anatomyone',
            name='textFive',
        ),
        migrations.RemoveField(
            model_name='anatomyone',
            name='textFiveLink',
        ),
        migrations.RemoveField(
            model_name='anatomyone',
            name='textFour',
        ),
        migrations.RemoveField(
            model_name='anatomyone',
            name='textFourLink',
        ),
        migrations.RemoveField(
            model_name='anatomyone',
            name='textSix',
        ),
        migrations.RemoveField(
            model_name='anatomyone',
            name='textSixLink',
        ),
        migrations.RemoveField(
            model_name='anatomyone',
            name='textThree',
        ),
        migrations.RemoveField(
            model_name='anatomyone',
            name='textThreeLink',
        ),
        migrations.RemoveField(
            model_name='anatomyone',
            name='textTwo',
        ),
        migrations.RemoveField(
            model_name='anatomyone',
            name='textTwoLink',
        ),
        migrations.RemoveField(
            model_name='anatomyone',
            name='topicByTopic',
        ),
        migrations.RemoveField(
            model_name='anatomyone',
            name='topicByTopicText',
        ),
        migrations.RemoveField(
            model_name='anatomyone',
            name='topicByTopicTextLink',
        ),
        migrations.RemoveField(
            model_name='anatomyone',
            name='type',
        ),
        migrations.RemoveField(
            model_name='anatomyone',
            name='typeOfFile',
        ),
        migrations.RemoveField(
            model_name='anatomytwo',
            name='revisionQuestions',
        ),
        migrations.RemoveField(
            model_name='anatomytwo',
            name='revisionQuestionsText',
        ),
        migrations.RemoveField(
            model_name='anatomytwo',
            name='revisionQuestionsTextLink',
        ),
        migrations.RemoveField(
            model_name='anatomytwo',
            name='textFive',
        ),
        migrations.RemoveField(
            model_name='anatomytwo',
            name='textFiveLink',
        ),
        migrations.RemoveField(
            model_name='anatomytwo',
            name='textFour',
        ),
        migrations.RemoveField(
            model_name='anatomytwo',
            name='textFourLink',
        ),
        migrations.RemoveField(
            model_name='anatomytwo',
            name='textSix',
        ),
        migrations.RemoveField(
            model_name='anatomytwo',
            name='textSixLink',
        ),
        migrations.RemoveField(
            model_name='anatomytwo',
            name='textThree',
        ),
        migrations.RemoveField(
            model_name='anatomytwo',
            name='textThreeLink',
        ),
        migrations.RemoveField(
            model_name='anatomytwo',
            name='textTwo',
        ),
        migrations.RemoveField(
            model_name='anatomytwo',
            name='textTwoLink',
        ),
        migrations.RemoveField(
            model_name='anatomytwo',
            name='topicByTopic',
        ),
        migrations.RemoveField(
            model_name='anatomytwo',
            name='topicByTopicText',
        ),
        migrations.RemoveField(
            model_name='anatomytwo',
            name='topicByTopicTextLink',
        ),
        migrations.RemoveField(
            model_name='anatomytwo',
            name='type',
        ),
        migrations.RemoveField(
            model_name='anatomytwo',
            name='typeOfFile',
        ),
        migrations.RemoveField(
            model_name='biochemistryone',
            name='revisionQuestions',
        ),
        migrations.RemoveField(
            model_name='biochemistryone',
            name='revisionQuestionsText',
        ),
        migrations.RemoveField(
            model_name='biochemistryone',
            name='revisionQuestionsTextLink',
        ),
        migrations.RemoveField(
            model_name='biochemistryone',
            name='textFive',
        ),
        migrations.RemoveField(
            model_name='biochemistryone',
            name='textFiveLink',
        ),
        migrations.RemoveField(
            model_name='biochemistryone',
            name='textFour',
        ),
        migrations.RemoveField(
            model_name='biochemistryone',
            name='textFourLink',
        ),
        migrations.RemoveField(
            model_name='biochemistryone',
            name='textSix',
        ),
        migrations.RemoveField(
            model_name='biochemistryone',
            name='textSixLink',
        ),
        migrations.RemoveField(
            model_name='biochemistryone',
            name='textThree',
        ),
        migrations.RemoveField(
            model_name='biochemistryone',
            name='textThreeLink',
        ),
        migrations.RemoveField(
            model_name='biochemistryone',
            name='textTwo',
        ),
        migrations.RemoveField(
            model_name='biochemistryone',
            name='textTwoLink',
        ),
        migrations.RemoveField(
            model_name='biochemistryone',
            name='topicByTopic',
        ),
        migrations.RemoveField(
            model_name='biochemistryone',
            name='topicByTopicText',
        ),
        migrations.RemoveField(
            model_name='biochemistryone',
            name='topicByTopicTextLink',
        ),
        migrations.RemoveField(
            model_name='biochemistryone',
            name='type',
        ),
        migrations.RemoveField(
            model_name='biochemistryone',
            name='typeOfFile',
        ),
        migrations.RemoveField(
            model_name='biochemistrytwo',
            name='revisionQuestions',
        ),
        migrations.RemoveField(
            model_name='biochemistrytwo',
            name='revisionQuestionsText',
        ),
        migrations.RemoveField(
            model_name='biochemistrytwo',
            name='revisionQuestionsTextLink',
        ),
        migrations.RemoveField(
            model_name='biochemistrytwo',
            name='textFive',
        ),
        migrations.RemoveField(
            model_name='biochemistrytwo',
            name='textFiveLink',
        ),
        migrations.RemoveField(
            model_name='biochemistrytwo',
            name='textFour',
        ),
        migrations.RemoveField(
            model_name='biochemistrytwo',
            name='textFourLink',
        ),
        migrations.RemoveField(
            model_name='biochemistrytwo',
            name='textSix',
        ),
        migrations.RemoveField(
            model_name='biochemistrytwo',
            name='textSixLink',
        ),
        migrations.RemoveField(
            model_name='biochemistrytwo',
            name='textThree',
        ),
        migrations.RemoveField(
            model_name='biochemistrytwo',
            name='textThreeLink',
        ),
        migrations.RemoveField(
            model_name='biochemistrytwo',
            name='textTwo',
        ),
        migrations.RemoveField(
            model_name='biochemistrytwo',
            name='textTwoLink',
        ),
        migrations.RemoveField(
            model_name='biochemistrytwo',
            name='topicByTopic',
        ),
        migrations.RemoveField(
            model_name='biochemistrytwo',
            name='topicByTopicText',
        ),
        migrations.RemoveField(
            model_name='biochemistrytwo',
            name='topicByTopicTextLink',
        ),
        migrations.RemoveField(
            model_name='biochemistrytwo',
            name='type',
        ),
        migrations.RemoveField(
            model_name='biochemistrytwo',
            name='typeOfFile',
        ),
        migrations.RemoveField(
            model_name='clinicalscienceone',
            name='revisionQuestions',
        ),
        migrations.RemoveField(
            model_name='clinicalscienceone',
            name='revisionQuestionsText',
        ),
        migrations.RemoveField(
            model_name='clinicalscienceone',
            name='revisionQuestionsTextLink',
        ),
        migrations.RemoveField(
            model_name='clinicalscienceone',
            name='textFive',
        ),
        migrations.RemoveField(
            model_name='clinicalscienceone',
            name='textFiveLink',
        ),
        migrations.RemoveField(
            model_name='clinicalscienceone',
            name='textFour',
        ),
        migrations.RemoveField(
            model_name='clinicalscienceone',
            name='textFourLink',
        ),
        migrations.RemoveField(
            model_name='clinicalscienceone',
            name='textSix',
        ),
        migrations.RemoveField(
            model_name='clinicalscienceone',
            name='textSixLink',
        ),
        migrations.RemoveField(
            model_name='clinicalscienceone',
            name='textThree',
        ),
        migrations.RemoveField(
            model_name='clinicalscienceone',
            name='textThreeLink',
        ),
        migrations.RemoveField(
            model_name='clinicalscienceone',
            name='textTwo',
        ),
        migrations.RemoveField(
            model_name='clinicalscienceone',
            name='textTwoLink',
        ),
        migrations.RemoveField(
            model_name='clinicalscienceone',
            name='topicByTopic',
        ),
        migrations.RemoveField(
            model_name='clinicalscienceone',
            name='topicByTopicText',
        ),
        migrations.RemoveField(
            model_name='clinicalscienceone',
            name='topicByTopicTextLink',
        ),
        migrations.RemoveField(
            model_name='clinicalscienceone',
            name='type',
        ),
        migrations.RemoveField(
            model_name='clinicalscienceone',
            name='typeOfFile',
        ),
        migrations.RemoveField(
            model_name='clinicalsciencetwo',
            name='revisionQuestions',
        ),
        migrations.RemoveField(
            model_name='clinicalsciencetwo',
            name='revisionQuestionsText',
        ),
        migrations.RemoveField(
            model_name='clinicalsciencetwo',
            name='revisionQuestionsTextLink',
        ),
        migrations.RemoveField(
            model_name='clinicalsciencetwo',
            name='textFive',
        ),
        migrations.RemoveField(
            model_name='clinicalsciencetwo',
            name='textFiveLink',
        ),
        migrations.RemoveField(
            model_name='clinicalsciencetwo',
            name='textFour',
        ),
        migrations.RemoveField(
            model_name='clinicalsciencetwo',
            name='textFourLink',
        ),
        migrations.RemoveField(
            model_name='clinicalsciencetwo',
            name='textSix',
        ),
        migrations.RemoveField(
            model_name='clinicalsciencetwo',
            name='textSixLink',
        ),
        migrations.RemoveField(
            model_name='clinicalsciencetwo',
            name='textThree',
        ),
        migrations.RemoveField(
            model_name='clinicalsciencetwo',
            name='textThreeLink',
        ),
        migrations.RemoveField(
            model_name='clinicalsciencetwo',
            name='textTwo',
        ),
        migrations.RemoveField(
            model_name='clinicalsciencetwo',
            name='textTwoLink',
        ),
        migrations.RemoveField(
            model_name='clinicalsciencetwo',
            name='topicByTopic',
        ),
        migrations.RemoveField(
            model_name='clinicalsciencetwo',
            name='topicByTopicText',
        ),
        migrations.RemoveField(
            model_name='clinicalsciencetwo',
            name='topicByTopicTextLink',
        ),
        migrations.RemoveField(
            model_name='clinicalsciencetwo',
            name='type',
        ),
        migrations.RemoveField(
            model_name='clinicalsciencetwo',
            name='typeOfFile',
        ),
        migrations.RemoveField(
            model_name='diagnosticsone',
            name='revisionQuestions',
        ),
        migrations.RemoveField(
            model_name='diagnosticsone',
            name='revisionQuestionsText',
        ),
        migrations.RemoveField(
            model_name='diagnosticsone',
            name='revisionQuestionsTextLink',
        ),
        migrations.RemoveField(
            model_name='diagnosticsone',
            name='textFive',
        ),
        migrations.RemoveField(
            model_name='diagnosticsone',
            name='textFiveLink',
        ),
        migrations.RemoveField(
            model_name='diagnosticsone',
            name='textFour',
        ),
        migrations.RemoveField(
            model_name='diagnosticsone',
            name='textFourLink',
        ),
        migrations.RemoveField(
            model_name='diagnosticsone',
            name='textSix',
        ),
        migrations.RemoveField(
            model_name='diagnosticsone',
            name='textSixLink',
        ),
        migrations.RemoveField(
            model_name='diagnosticsone',
            name='textThree',
        ),
        migrations.RemoveField(
            model_name='diagnosticsone',
            name='textThreeLink',
        ),
        migrations.RemoveField(
            model_name='diagnosticsone',
            name='textTwo',
        ),
        migrations.RemoveField(
            model_name='diagnosticsone',
            name='textTwoLink',
        ),
        migrations.RemoveField(
            model_name='diagnosticsone',
            name='topicByTopic',
        ),
        migrations.RemoveField(
            model_name='diagnosticsone',
            name='topicByTopicText',
        ),
        migrations.RemoveField(
            model_name='diagnosticsone',
            name='topicByTopicTextLink',
        ),
        migrations.RemoveField(
            model_name='diagnosticsone',
            name='type',
        ),
        migrations.RemoveField(
            model_name='diagnosticsone',
            name='typeOfFile',
        ),
        migrations.RemoveField(
            model_name='diagnosticstwo',
            name='revisionQuestions',
        ),
        migrations.RemoveField(
            model_name='diagnosticstwo',
            name='revisionQuestionsText',
        ),
        migrations.RemoveField(
            model_name='diagnosticstwo',
            name='revisionQuestionsTextLink',
        ),
        migrations.RemoveField(
            model_name='diagnosticstwo',
            name='textFive',
        ),
        migrations.RemoveField(
            model_name='diagnosticstwo',
            name='textFiveLink',
        ),
        migrations.RemoveField(
            model_name='diagnosticstwo',
            name='textFour',
        ),
        migrations.RemoveField(
            model_name='diagnosticstwo',
            name='textFourLink',
        ),
        migrations.RemoveField(
            model_name='diagnosticstwo',
            name='textSix',
        ),
        migrations.RemoveField(
            model_name='diagnosticstwo',
            name='textSixLink',
        ),
        migrations.RemoveField(
            model_name='diagnosticstwo',
            name='textThree',
        ),
        migrations.RemoveField(
            model_name='diagnosticstwo',
            name='textThreeLink',
        ),
        migrations.RemoveField(
            model_name='diagnosticstwo',
            name='textTwo',
        ),
        migrations.RemoveField(
            model_name='diagnosticstwo',
            name='textTwoLink',
        ),
        migrations.RemoveField(
            model_name='diagnosticstwo',
            name='topicByTopic',
        ),
        migrations.RemoveField(
            model_name='diagnosticstwo',
            name='topicByTopicText',
        ),
        migrations.RemoveField(
            model_name='diagnosticstwo',
            name='topicByTopicTextLink',
        ),
        migrations.RemoveField(
            model_name='diagnosticstwo',
            name='type',
        ),
        migrations.RemoveField(
            model_name='diagnosticstwo',
            name='typeOfFile',
        ),
        migrations.RemoveField(
            model_name='labscienceone',
            name='revisionQuestions',
        ),
        migrations.RemoveField(
            model_name='labscienceone',
            name='revisionQuestionsText',
        ),
        migrations.RemoveField(
            model_name='labscienceone',
            name='revisionQuestionsTextLink',
        ),
        migrations.RemoveField(
            model_name='labscienceone',
            name='textFive',
        ),
        migrations.RemoveField(
            model_name='labscienceone',
            name='textFiveLink',
        ),
        migrations.RemoveField(
            model_name='labscienceone',
            name='textFour',
        ),
        migrations.RemoveField(
            model_name='labscienceone',
            name='textFourLink',
        ),
        migrations.RemoveField(
            model_name='labscienceone',
            name='textSix',
        ),
        migrations.RemoveField(
            model_name='labscienceone',
            name='textSixLink',
        ),
        migrations.RemoveField(
            model_name='labscienceone',
            name='textThree',
        ),
        migrations.RemoveField(
            model_name='labscienceone',
            name='textThreeLink',
        ),
        migrations.RemoveField(
            model_name='labscienceone',
            name='textTwo',
        ),
        migrations.RemoveField(
            model_name='labscienceone',
            name='textTwoLink',
        ),
        migrations.RemoveField(
            model_name='labscienceone',
            name='topicByTopic',
        ),
        migrations.RemoveField(
            model_name='labscienceone',
            name='topicByTopicText',
        ),
        migrations.RemoveField(
            model_name='labscienceone',
            name='topicByTopicTextLink',
        ),
        migrations.RemoveField(
            model_name='labscienceone',
            name='type',
        ),
        migrations.RemoveField(
            model_name='labscienceone',
            name='typeOfFile',
        ),
        migrations.RemoveField(
            model_name='labsciencetwo',
            name='revisionQuestions',
        ),
        migrations.RemoveField(
            model_name='labsciencetwo',
            name='revisionQuestionsText',
        ),
        migrations.RemoveField(
            model_name='labsciencetwo',
            name='revisionQuestionsTextLink',
        ),
        migrations.RemoveField(
            model_name='labsciencetwo',
            name='textFive',
        ),
        migrations.RemoveField(
            model_name='labsciencetwo',
            name='textFiveLink',
        ),
        migrations.RemoveField(
            model_name='labsciencetwo',
            name='textFour',
        ),
        migrations.RemoveField(
            model_name='labsciencetwo',
            name='textFourLink',
        ),
        migrations.RemoveField(
            model_name='labsciencetwo',
            name='textSix',
        ),
        migrations.RemoveField(
            model_name='labsciencetwo',
            name='textSixLink',
        ),
        migrations.RemoveField(
            model_name='labsciencetwo',
            name='textThree',
        ),
        migrations.RemoveField(
            model_name='labsciencetwo',
            name='textThreeLink',
        ),
        migrations.RemoveField(
            model_name='labsciencetwo',
            name='textTwo',
        ),
        migrations.RemoveField(
            model_name='labsciencetwo',
            name='textTwoLink',
        ),
        migrations.RemoveField(
            model_name='labsciencetwo',
            name='topicByTopic',
        ),
        migrations.RemoveField(
            model_name='labsciencetwo',
            name='topicByTopicText',
        ),
        migrations.RemoveField(
            model_name='labsciencetwo',
            name='topicByTopicTextLink',
        ),
        migrations.RemoveField(
            model_name='labsciencetwo',
            name='type',
        ),
        migrations.RemoveField(
            model_name='labsciencetwo',
            name='typeOfFile',
        ),
        migrations.RemoveField(
            model_name='pathologyone',
            name='revisionQuestions',
        ),
        migrations.RemoveField(
            model_name='pathologyone',
            name='revisionQuestionsText',
        ),
        migrations.RemoveField(
            model_name='pathologyone',
            name='revisionQuestionsTextLink',
        ),
        migrations.RemoveField(
            model_name='pathologyone',
            name='textFive',
        ),
        migrations.RemoveField(
            model_name='pathologyone',
            name='textFiveLink',
        ),
        migrations.RemoveField(
            model_name='pathologyone',
            name='textFour',
        ),
        migrations.RemoveField(
            model_name='pathologyone',
            name='textFourLink',
        ),
        migrations.RemoveField(
            model_name='pathologyone',
            name='textSix',
        ),
        migrations.RemoveField(
            model_name='pathologyone',
            name='textSixLink',
        ),
        migrations.RemoveField(
            model_name='pathologyone',
            name='textThree',
        ),
        migrations.RemoveField(
            model_name='pathologyone',
            name='textThreeLink',
        ),
        migrations.RemoveField(
            model_name='pathologyone',
            name='textTwo',
        ),
        migrations.RemoveField(
            model_name='pathologyone',
            name='textTwoLink',
        ),
        migrations.RemoveField(
            model_name='pathologyone',
            name='topicByTopic',
        ),
        migrations.RemoveField(
            model_name='pathologyone',
            name='topicByTopicText',
        ),
        migrations.RemoveField(
            model_name='pathologyone',
            name='topicByTopicTextLink',
        ),
        migrations.RemoveField(
            model_name='pathologyone',
            name='type',
        ),
        migrations.RemoveField(
            model_name='pathologyone',
            name='typeOfFile',
        ),
        migrations.RemoveField(
            model_name='pathologytwo',
            name='revisionQuestions',
        ),
        migrations.RemoveField(
            model_name='pathologytwo',
            name='revisionQuestionsText',
        ),
        migrations.RemoveField(
            model_name='pathologytwo',
            name='revisionQuestionsTextLink',
        ),
        migrations.RemoveField(
            model_name='pathologytwo',
            name='textFive',
        ),
        migrations.RemoveField(
            model_name='pathologytwo',
            name='textFiveLink',
        ),
        migrations.RemoveField(
            model_name='pathologytwo',
            name='textFour',
        ),
        migrations.RemoveField(
            model_name='pathologytwo',
            name='textFourLink',
        ),
        migrations.RemoveField(
            model_name='pathologytwo',
            name='textSix',
        ),
        migrations.RemoveField(
            model_name='pathologytwo',
            name='textSixLink',
        ),
        migrations.RemoveField(
            model_name='pathologytwo',
            name='textThree',
        ),
        migrations.RemoveField(
            model_name='pathologytwo',
            name='textThreeLink',
        ),
        migrations.RemoveField(
            model_name='pathologytwo',
            name='textTwo',
        ),
        migrations.RemoveField(
            model_name='pathologytwo',
            name='textTwoLink',
        ),
        migrations.RemoveField(
            model_name='pathologytwo',
            name='topicByTopic',
        ),
        migrations.RemoveField(
            model_name='pathologytwo',
            name='topicByTopicText',
        ),
        migrations.RemoveField(
            model_name='pathologytwo',
            name='topicByTopicTextLink',
        ),
        migrations.RemoveField(
            model_name='pathologytwo',
            name='type',
        ),
        migrations.RemoveField(
            model_name='pathologytwo',
            name='typeOfFile',
        ),
        migrations.RemoveField(
            model_name='physiologyone',
            name='revisionQuestions',
        ),
        migrations.RemoveField(
            model_name='physiologyone',
            name='revisionQuestionsText',
        ),
        migrations.RemoveField(
            model_name='physiologyone',
            name='revisionQuestionsTextLink',
        ),
        migrations.RemoveField(
            model_name='physiologyone',
            name='textFive',
        ),
        migrations.RemoveField(
            model_name='physiologyone',
            name='textFiveLink',
        ),
        migrations.RemoveField(
            model_name='physiologyone',
            name='textFour',
        ),
        migrations.RemoveField(
            model_name='physiologyone',
            name='textFourLink',
        ),
        migrations.RemoveField(
            model_name='physiologyone',
            name='textSix',
        ),
        migrations.RemoveField(
            model_name='physiologyone',
            name='textSixLink',
        ),
        migrations.RemoveField(
            model_name='physiologyone',
            name='textThree',
        ),
        migrations.RemoveField(
            model_name='physiologyone',
            name='textThreeLink',
        ),
        migrations.RemoveField(
            model_name='physiologyone',
            name='textTwo',
        ),
        migrations.RemoveField(
            model_name='physiologyone',
            name='textTwoLink',
        ),
        migrations.RemoveField(
            model_name='physiologyone',
            name='topicByTopic',
        ),
        migrations.RemoveField(
            model_name='physiologyone',
            name='topicByTopicText',
        ),
        migrations.RemoveField(
            model_name='physiologyone',
            name='topicByTopicTextLink',
        ),
        migrations.RemoveField(
            model_name='physiologyone',
            name='type',
        ),
        migrations.RemoveField(
            model_name='physiologyone',
            name='typeOfFile',
        ),
        migrations.RemoveField(
            model_name='physiologytwo',
            name='revisionQuestions',
        ),
        migrations.RemoveField(
            model_name='physiologytwo',
            name='revisionQuestionsText',
        ),
        migrations.RemoveField(
            model_name='physiologytwo',
            name='revisionQuestionsTextLink',
        ),
        migrations.RemoveField(
            model_name='physiologytwo',
            name='textFive',
        ),
        migrations.RemoveField(
            model_name='physiologytwo',
            name='textFiveLink',
        ),
        migrations.RemoveField(
            model_name='physiologytwo',
            name='textFour',
        ),
        migrations.RemoveField(
            model_name='physiologytwo',
            name='textFourLink',
        ),
        migrations.RemoveField(
            model_name='physiologytwo',
            name='textSix',
        ),
        migrations.RemoveField(
            model_name='physiologytwo',
            name='textSixLink',
        ),
        migrations.RemoveField(
            model_name='physiologytwo',
            name='textThree',
        ),
        migrations.RemoveField(
            model_name='physiologytwo',
            name='textThreeLink',
        ),
        migrations.RemoveField(
            model_name='physiologytwo',
            name='textTwo',
        ),
        migrations.RemoveField(
            model_name='physiologytwo',
            name='textTwoLink',
        ),
        migrations.RemoveField(
            model_name='physiologytwo',
            name='topicByTopic',
        ),
        migrations.RemoveField(
            model_name='physiologytwo',
            name='topicByTopicText',
        ),
        migrations.RemoveField(
            model_name='physiologytwo',
            name='topicByTopicTextLink',
        ),
        migrations.RemoveField(
            model_name='physiologytwo',
            name='type',
        ),
        migrations.RemoveField(
            model_name='physiologytwo',
            name='typeOfFile',
        ),
        migrations.RemoveField(
            model_name='publichealthone',
            name='revisionQuestions',
        ),
        migrations.RemoveField(
            model_name='publichealthone',
            name='revisionQuestionsText',
        ),
        migrations.RemoveField(
            model_name='publichealthone',
            name='revisionQuestionsTextLink',
        ),
        migrations.RemoveField(
            model_name='publichealthone',
            name='textFive',
        ),
        migrations.RemoveField(
            model_name='publichealthone',
            name='textFiveLink',
        ),
        migrations.RemoveField(
            model_name='publichealthone',
            name='textFour',
        ),
        migrations.RemoveField(
            model_name='publichealthone',
            name='textFourLink',
        ),
        migrations.RemoveField(
            model_name='publichealthone',
            name='textSix',
        ),
        migrations.RemoveField(
            model_name='publichealthone',
            name='textSixLink',
        ),
        migrations.RemoveField(
            model_name='publichealthone',
            name='textThree',
        ),
        migrations.RemoveField(
            model_name='publichealthone',
            name='textThreeLink',
        ),
        migrations.RemoveField(
            model_name='publichealthone',
            name='textTwo',
        ),
        migrations.RemoveField(
            model_name='publichealthone',
            name='textTwoLink',
        ),
        migrations.RemoveField(
            model_name='publichealthone',
            name='topicByTopic',
        ),
        migrations.RemoveField(
            model_name='publichealthone',
            name='topicByTopicText',
        ),
        migrations.RemoveField(
            model_name='publichealthone',
            name='topicByTopicTextLink',
        ),
        migrations.RemoveField(
            model_name='publichealthone',
            name='type',
        ),
        migrations.RemoveField(
            model_name='publichealthone',
            name='typeOfFile',
        ),
        migrations.RemoveField(
            model_name='publichealthtwo',
            name='revisionQuestions',
        ),
        migrations.RemoveField(
            model_name='publichealthtwo',
            name='revisionQuestionsText',
        ),
        migrations.RemoveField(
            model_name='publichealthtwo',
            name='revisionQuestionsTextLink',
        ),
        migrations.RemoveField(
            model_name='publichealthtwo',
            name='textFive',
        ),
        migrations.RemoveField(
            model_name='publichealthtwo',
            name='textFiveLink',
        ),
        migrations.RemoveField(
            model_name='publichealthtwo',
            name='textFour',
        ),
        migrations.RemoveField(
            model_name='publichealthtwo',
            name='textFourLink',
        ),
        migrations.RemoveField(
            model_name='publichealthtwo',
            name='textSix',
        ),
        migrations.RemoveField(
            model_name='publichealthtwo',
            name='textSixLink',
        ),
        migrations.RemoveField(
            model_name='publichealthtwo',
            name='textThree',
        ),
        migrations.RemoveField(
            model_name='publichealthtwo',
            name='textThreeLink',
        ),
        migrations.RemoveField(
            model_name='publichealthtwo',
            name='textTwo',
        ),
        migrations.RemoveField(
            model_name='publichealthtwo',
            name='textTwoLink',
        ),
        migrations.RemoveField(
            model_name='publichealthtwo',
            name='topicByTopic',
        ),
        migrations.RemoveField(
            model_name='publichealthtwo',
            name='topicByTopicText',
        ),
        migrations.RemoveField(
            model_name='publichealthtwo',
            name='topicByTopicTextLink',
        ),
        migrations.RemoveField(
            model_name='publichealthtwo',
            name='type',
        ),
        migrations.RemoveField(
            model_name='publichealthtwo',
            name='typeOfFile',
        ),
        migrations.RemoveField(
            model_name='societyandmedicineone',
            name='revisionQuestions',
        ),
        migrations.RemoveField(
            model_name='societyandmedicineone',
            name='revisionQuestionsText',
        ),
        migrations.RemoveField(
            model_name='societyandmedicineone',
            name='revisionQuestionsTextLink',
        ),
        migrations.RemoveField(
            model_name='societyandmedicineone',
            name='textFive',
        ),
        migrations.RemoveField(
            model_name='societyandmedicineone',
            name='textFiveLink',
        ),
        migrations.RemoveField(
            model_name='societyandmedicineone',
            name='textFour',
        ),
        migrations.RemoveField(
            model_name='societyandmedicineone',
            name='textFourLink',
        ),
        migrations.RemoveField(
            model_name='societyandmedicineone',
            name='textSix',
        ),
        migrations.RemoveField(
            model_name='societyandmedicineone',
            name='textSixLink',
        ),
        migrations.RemoveField(
            model_name='societyandmedicineone',
            name='textThree',
        ),
        migrations.RemoveField(
            model_name='societyandmedicineone',
            name='textThreeLink',
        ),
        migrations.RemoveField(
            model_name='societyandmedicineone',
            name='textTwo',
        ),
        migrations.RemoveField(
            model_name='societyandmedicineone',
            name='textTwoLink',
        ),
        migrations.RemoveField(
            model_name='societyandmedicineone',
            name='topicByTopic',
        ),
        migrations.RemoveField(
            model_name='societyandmedicineone',
            name='topicByTopicText',
        ),
        migrations.RemoveField(
            model_name='societyandmedicineone',
            name='topicByTopicTextLink',
        ),
        migrations.RemoveField(
            model_name='societyandmedicineone',
            name='type',
        ),
        migrations.RemoveField(
            model_name='societyandmedicineone',
            name='typeOfFile',
        ),
        migrations.RemoveField(
            model_name='societyandmedicinetwo',
            name='revisionQuestions',
        ),
        migrations.RemoveField(
            model_name='societyandmedicinetwo',
            name='revisionQuestionsText',
        ),
        migrations.RemoveField(
            model_name='societyandmedicinetwo',
            name='revisionQuestionsTextLink',
        ),
        migrations.RemoveField(
            model_name='societyandmedicinetwo',
            name='textFive',
        ),
        migrations.RemoveField(
            model_name='societyandmedicinetwo',
            name='textFiveLink',
        ),
        migrations.RemoveField(
            model_name='societyandmedicinetwo',
            name='textFour',
        ),
        migrations.RemoveField(
            model_name='societyandmedicinetwo',
            name='textFourLink',
        ),
        migrations.RemoveField(
            model_name='societyandmedicinetwo',
            name='textSix',
        ),
        migrations.RemoveField(
            model_name='societyandmedicinetwo',
            name='textSixLink',
        ),
        migrations.RemoveField(
            model_name='societyandmedicinetwo',
            name='textThree',
        ),
        migrations.RemoveField(
            model_name='societyandmedicinetwo',
            name='textThreeLink',
        ),
        migrations.RemoveField(
            model_name='societyandmedicinetwo',
            name='textTwo',
        ),
        migrations.RemoveField(
            model_name='societyandmedicinetwo',
            name='textTwoLink',
        ),
        migrations.RemoveField(
            model_name='societyandmedicinetwo',
            name='topicByTopic',
        ),
        migrations.RemoveField(
            model_name='societyandmedicinetwo',
            name='topicByTopicText',
        ),
        migrations.RemoveField(
            model_name='societyandmedicinetwo',
            name='topicByTopicTextLink',
        ),
        migrations.RemoveField(
            model_name='societyandmedicinetwo',
            name='type',
        ),
        migrations.RemoveField(
            model_name='societyandmedicinetwo',
            name='typeOfFile',
        ),
        migrations.RemoveField(
            model_name='therapeuticsone',
            name='revisionQuestions',
        ),
        migrations.RemoveField(
            model_name='therapeuticsone',
            name='revisionQuestionsText',
        ),
        migrations.RemoveField(
            model_name='therapeuticsone',
            name='revisionQuestionsTextLink',
        ),
        migrations.RemoveField(
            model_name='therapeuticsone',
            name='textFive',
        ),
        migrations.RemoveField(
            model_name='therapeuticsone',
            name='textFiveLink',
        ),
        migrations.RemoveField(
            model_name='therapeuticsone',
            name='textFour',
        ),
        migrations.RemoveField(
            model_name='therapeuticsone',
            name='textFourLink',
        ),
        migrations.RemoveField(
            model_name='therapeuticsone',
            name='textSix',
        ),
        migrations.RemoveField(
            model_name='therapeuticsone',
            name='textSixLink',
        ),
        migrations.RemoveField(
            model_name='therapeuticsone',
            name='textThree',
        ),
        migrations.RemoveField(
            model_name='therapeuticsone',
            name='textThreeLink',
        ),
        migrations.RemoveField(
            model_name='therapeuticsone',
            name='textTwo',
        ),
        migrations.RemoveField(
            model_name='therapeuticsone',
            name='textTwoLink',
        ),
        migrations.RemoveField(
            model_name='therapeuticsone',
            name='topicByTopic',
        ),
        migrations.RemoveField(
            model_name='therapeuticsone',
            name='topicByTopicText',
        ),
        migrations.RemoveField(
            model_name='therapeuticsone',
            name='topicByTopicTextLink',
        ),
        migrations.RemoveField(
            model_name='therapeuticsone',
            name='type',
        ),
        migrations.RemoveField(
            model_name='therapeuticsone',
            name='typeOfFile',
        ),
        migrations.RemoveField(
            model_name='therapeuticstwo',
            name='revisionQuestions',
        ),
        migrations.RemoveField(
            model_name='therapeuticstwo',
            name='revisionQuestionsText',
        ),
        migrations.RemoveField(
            model_name='therapeuticstwo',
            name='revisionQuestionsTextLink',
        ),
        migrations.RemoveField(
            model_name='therapeuticstwo',
            name='textFive',
        ),
        migrations.RemoveField(
            model_name='therapeuticstwo',
            name='textFiveLink',
        ),
        migrations.RemoveField(
            model_name='therapeuticstwo',
            name='textFour',
        ),
        migrations.RemoveField(
            model_name='therapeuticstwo',
            name='textFourLink',
        ),
        migrations.RemoveField(
            model_name='therapeuticstwo',
            name='textSix',
        ),
        migrations.RemoveField(
            model_name='therapeuticstwo',
            name='textSixLink',
        ),
        migrations.RemoveField(
            model_name='therapeuticstwo',
            name='textThree',
        ),
        migrations.RemoveField(
            model_name='therapeuticstwo',
            name='textThreeLink',
        ),
        migrations.RemoveField(
            model_name='therapeuticstwo',
            name='textTwo',
        ),
        migrations.RemoveField(
            model_name='therapeuticstwo',
            name='textTwoLink',
        ),
        migrations.RemoveField(
            model_name='therapeuticstwo',
            name='topicByTopic',
        ),
        migrations.RemoveField(
            model_name='therapeuticstwo',
            name='topicByTopicText',
        ),
        migrations.RemoveField(
            model_name='therapeuticstwo',
            name='topicByTopicTextLink',
        ),
        migrations.RemoveField(
            model_name='therapeuticstwo',
            name='type',
        ),
        migrations.RemoveField(
            model_name='therapeuticstwo',
            name='typeOfFile',
        ),
    ]
