# Generated by Django 5.2 on 2025-05-03 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_anatomyonetbt_anatomytwotbt_biochemistryonetbt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anatomyone',
            name='textFive',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anatomyone',
            name='textFiveLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anatomyone',
            name='textFour',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anatomyone',
            name='textFourLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anatomyone',
            name='textSeven',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anatomyone',
            name='textSevenLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anatomyone',
            name='textSix',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anatomyone',
            name='textSixLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anatomyone',
            name='textThree',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anatomyone',
            name='textThreeLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anatomyone',
            name='textTwo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anatomyone',
            name='textTwoLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anatomytwo',
            name='textFive',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anatomytwo',
            name='textFiveLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anatomytwo',
            name='textFour',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anatomytwo',
            name='textFourLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anatomytwo',
            name='textSeven',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anatomytwo',
            name='textSevenLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anatomytwo',
            name='textSix',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anatomytwo',
            name='textSixLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anatomytwo',
            name='textThree',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anatomytwo',
            name='textThreeLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anatomytwo',
            name='textTwo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anatomytwo',
            name='textTwoLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biochemistryone',
            name='textFive',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biochemistryone',
            name='textFiveLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biochemistryone',
            name='textFour',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biochemistryone',
            name='textFourLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biochemistryone',
            name='textSeven',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biochemistryone',
            name='textSevenLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biochemistryone',
            name='textSix',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biochemistryone',
            name='textSixLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biochemistryone',
            name='textThree',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biochemistryone',
            name='textThreeLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biochemistryone',
            name='textTwo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biochemistryone',
            name='textTwoLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biochemistrytwo',
            name='textFive',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biochemistrytwo',
            name='textFiveLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biochemistrytwo',
            name='textFour',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biochemistrytwo',
            name='textFourLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biochemistrytwo',
            name='textSeven',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biochemistrytwo',
            name='textSevenLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biochemistrytwo',
            name='textSix',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biochemistrytwo',
            name='textSixLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biochemistrytwo',
            name='textThree',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biochemistrytwo',
            name='textThreeLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biochemistrytwo',
            name='textTwo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biochemistrytwo',
            name='textTwoLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinicalscienceone',
            name='textFive',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinicalscienceone',
            name='textFiveLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinicalscienceone',
            name='textFour',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinicalscienceone',
            name='textFourLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinicalscienceone',
            name='textSeven',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinicalscienceone',
            name='textSevenLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinicalscienceone',
            name='textSix',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinicalscienceone',
            name='textSixLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinicalscienceone',
            name='textThree',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinicalscienceone',
            name='textThreeLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinicalscienceone',
            name='textTwo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinicalscienceone',
            name='textTwoLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinicalsciencetwo',
            name='textFive',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinicalsciencetwo',
            name='textFiveLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinicalsciencetwo',
            name='textFour',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinicalsciencetwo',
            name='textFourLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinicalsciencetwo',
            name='textSeven',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinicalsciencetwo',
            name='textSevenLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinicalsciencetwo',
            name='textSix',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinicalsciencetwo',
            name='textSixLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinicalsciencetwo',
            name='textThree',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinicalsciencetwo',
            name='textThreeLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinicalsciencetwo',
            name='textTwo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinicalsciencetwo',
            name='textTwoLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticsone',
            name='textFive',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticsone',
            name='textFiveLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticsone',
            name='textFour',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticsone',
            name='textFourLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticsone',
            name='textSeven',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticsone',
            name='textSevenLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticsone',
            name='textSix',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticsone',
            name='textSixLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticsone',
            name='textThree',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticsone',
            name='textThreeLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticsone',
            name='textTwo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticsone',
            name='textTwoLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticstwo',
            name='textFive',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticstwo',
            name='textFiveLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticstwo',
            name='textFour',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticstwo',
            name='textFourLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticstwo',
            name='textSeven',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticstwo',
            name='textSevenLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticstwo',
            name='textSix',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticstwo',
            name='textSixLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticstwo',
            name='textThree',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticstwo',
            name='textThreeLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticstwo',
            name='textTwo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticstwo',
            name='textTwoLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labscienceone',
            name='textFive',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labscienceone',
            name='textFiveLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labscienceone',
            name='textFour',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labscienceone',
            name='textFourLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labscienceone',
            name='textSeven',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labscienceone',
            name='textSevenLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labscienceone',
            name='textSix',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labscienceone',
            name='textSixLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labscienceone',
            name='textThree',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labscienceone',
            name='textThreeLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labscienceone',
            name='textTwo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labscienceone',
            name='textTwoLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labsciencetwo',
            name='textFive',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labsciencetwo',
            name='textFiveLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labsciencetwo',
            name='textFour',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labsciencetwo',
            name='textFourLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labsciencetwo',
            name='textSeven',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labsciencetwo',
            name='textSevenLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labsciencetwo',
            name='textSix',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labsciencetwo',
            name='textSixLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labsciencetwo',
            name='textThree',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labsciencetwo',
            name='textThreeLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labsciencetwo',
            name='textTwo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labsciencetwo',
            name='textTwoLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pathologyone',
            name='textFive',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pathologyone',
            name='textFiveLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pathologyone',
            name='textFour',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pathologyone',
            name='textFourLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pathologyone',
            name='textSeven',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pathologyone',
            name='textSevenLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pathologyone',
            name='textSix',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pathologyone',
            name='textSixLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pathologyone',
            name='textThree',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pathologyone',
            name='textThreeLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pathologyone',
            name='textTwo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pathologyone',
            name='textTwoLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pathologytwo',
            name='textFive',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pathologytwo',
            name='textFiveLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pathologytwo',
            name='textFour',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pathologytwo',
            name='textFourLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pathologytwo',
            name='textSeven',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pathologytwo',
            name='textSevenLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pathologytwo',
            name='textSix',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pathologytwo',
            name='textSixLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pathologytwo',
            name='textThree',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pathologytwo',
            name='textThreeLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pathologytwo',
            name='textTwo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pathologytwo',
            name='textTwoLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='physiologyone',
            name='textFive',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='physiologyone',
            name='textFiveLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='physiologyone',
            name='textFour',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='physiologyone',
            name='textFourLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='physiologyone',
            name='textSeven',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='physiologyone',
            name='textSevenLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='physiologyone',
            name='textSix',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='physiologyone',
            name='textSixLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='physiologyone',
            name='textThree',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='physiologyone',
            name='textThreeLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='physiologyone',
            name='textTwo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='physiologyone',
            name='textTwoLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='physiologytwo',
            name='textFive',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='physiologytwo',
            name='textFiveLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='physiologytwo',
            name='textFour',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='physiologytwo',
            name='textFourLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='physiologytwo',
            name='textSeven',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='physiologytwo',
            name='textSevenLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='physiologytwo',
            name='textSix',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='physiologytwo',
            name='textSixLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='physiologytwo',
            name='textThree',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='physiologytwo',
            name='textThreeLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='physiologytwo',
            name='textTwo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='physiologytwo',
            name='textTwoLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publichealthone',
            name='textFive',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publichealthone',
            name='textFiveLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publichealthone',
            name='textFour',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publichealthone',
            name='textFourLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publichealthone',
            name='textSeven',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publichealthone',
            name='textSevenLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publichealthone',
            name='textSix',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publichealthone',
            name='textSixLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publichealthone',
            name='textThree',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publichealthone',
            name='textThreeLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publichealthone',
            name='textTwo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publichealthone',
            name='textTwoLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publichealthtwo',
            name='textFive',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publichealthtwo',
            name='textFiveLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publichealthtwo',
            name='textFour',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publichealthtwo',
            name='textFourLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publichealthtwo',
            name='textSeven',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publichealthtwo',
            name='textSevenLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publichealthtwo',
            name='textSix',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publichealthtwo',
            name='textSixLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publichealthtwo',
            name='textThree',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publichealthtwo',
            name='textThreeLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publichealthtwo',
            name='textTwo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publichealthtwo',
            name='textTwoLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='societyandmedicineone',
            name='textFive',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='societyandmedicineone',
            name='textFiveLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='societyandmedicineone',
            name='textFour',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='societyandmedicineone',
            name='textFourLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='societyandmedicineone',
            name='textSeven',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='societyandmedicineone',
            name='textSevenLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='societyandmedicineone',
            name='textSix',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='societyandmedicineone',
            name='textSixLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='societyandmedicineone',
            name='textThree',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='societyandmedicineone',
            name='textThreeLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='societyandmedicineone',
            name='textTwo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='societyandmedicineone',
            name='textTwoLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='societyandmedicinetwo',
            name='textFive',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='societyandmedicinetwo',
            name='textFiveLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='societyandmedicinetwo',
            name='textFour',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='societyandmedicinetwo',
            name='textFourLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='societyandmedicinetwo',
            name='textSeven',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='societyandmedicinetwo',
            name='textSevenLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='societyandmedicinetwo',
            name='textSix',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='societyandmedicinetwo',
            name='textSixLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='societyandmedicinetwo',
            name='textThree',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='societyandmedicinetwo',
            name='textThreeLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='societyandmedicinetwo',
            name='textTwo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='societyandmedicinetwo',
            name='textTwoLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='therapeuticsone',
            name='textFive',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='therapeuticsone',
            name='textFiveLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='therapeuticsone',
            name='textFour',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='therapeuticsone',
            name='textFourLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='therapeuticsone',
            name='textSeven',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='therapeuticsone',
            name='textSevenLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='therapeuticsone',
            name='textSix',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='therapeuticsone',
            name='textSixLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='therapeuticsone',
            name='textThree',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='therapeuticsone',
            name='textThreeLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='therapeuticsone',
            name='textTwo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='therapeuticsone',
            name='textTwoLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='therapeuticstwo',
            name='textFive',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='therapeuticstwo',
            name='textFiveLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='therapeuticstwo',
            name='textFour',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='therapeuticstwo',
            name='textFourLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='therapeuticstwo',
            name='textSeven',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='therapeuticstwo',
            name='textSevenLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='therapeuticstwo',
            name='textSix',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='therapeuticstwo',
            name='textSixLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='therapeuticstwo',
            name='textThree',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='therapeuticstwo',
            name='textThreeLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='therapeuticstwo',
            name='textTwo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='therapeuticstwo',
            name='textTwoLink',
            field=models.TextField(blank=True, null=True),
        ),
    ]
